<div style="margin: 0 10px;">
	<?php
		$this->renderFlashMessage();

		if($this->subnet->isPendingServiceRequest()) {
			$this->renderTemplate('/flash-messages/info.phtml', array(
				'content' => 'This subnet is currently pending a service request. No reverse DNS records updates may be made at this time.'
			));
		}
	?>

	<table class="form" width="100%" border="0" cellspacing="2" cellpadding="3">
		<tr>
			<td width="15%" class="fieldlabel">Subnet CIDR</td>
			<td width="35%" class="fieldarea"><?php echo $this->subnet->getCIDRIpAddress(); ?></td>
			<td width="15%" class="fieldlabel">SWIP</td>
			<td width="35%" class="fieldarea"><?php echo $this->subnet->isSwip() ? 'Yes' : 'No'; ?></td>
		</tr>
		<tr>
			<td width="15%" class="fieldlabel">Device</td>
			<td width="35%" class="fieldarea">
			<?php
				if(isset($this->device)) {
					$device_id = $this->device->getId();
					$device_name = $this->device->getName();

					$device_url = ColoCrossing_Utilities::buildUrl($this->base_url, array(
						'controller' => 'devices',
						'action' => 'view',
						'id' => $device_id
					));

					echo '<a href="' . $device_url . '">' . $device_name . '</a>';
				} else {
					echo 'Unassigned';
				}
			?>
			</td>
			<td width="15%" class="fieldlabel">Zone</td>
			<td width="35%" class="fieldarea"><?php echo $this->subnet->getSubzone(); ?></td>
		</tr>
		<tr>
			<td width="15%" class="fieldlabel">First Usable IP</td>
			<td width="35%" class="fieldarea"><?php echo $this->subnet->getFirstUsableIpAddress(); ?></td>
			<td width="15%" class="fieldlabel">Mask</td>
			<td width="35%" class="fieldarea"><?php echo $this->subnet->getMask(); ?></td>
		</tr>
		<tr>
			<td width="15%" class="fieldlabel">Last Usable IP</td>
			<td width="35%" class="fieldarea"><?php echo $this->subnet->getLastUsableIpAddress(); ?></td>
			<td width="15%" class="fieldlabel">Gateway</td>
			<td width="35%" class="fieldarea"><?php echo $this->subnet->getGateway(); ?></td>
		</tr>
		<tr>
			<td width="15%" class="fieldlabel">Usable Addresses</td>
			<td width="35%" class="fieldarea"><?php echo $this->subnet->getNumberOfUsableIpAddresses(); ?></td>
			<td width="15%" class="fieldlabel">Broadcast</td>
			<td width="35%" class="fieldarea"><?php echo $this->subnet->getBroadcast(); ?></td>
		</tr>
		<tr>
			<td width="15%" class="fieldlabel">Total Addresses</td>
			<td width="35%" class="fieldarea"><?php echo $this->subnet->getNumberOfIpAddresses(); ?></td>
		</tr>
	</table>

<?php
	if($this->subnet->isReverseDnsEnabled()) {
		$this->renderTemplate('/subnets/_rdns_records.phtml', array(
			'base_url' => $this->base_url,
			'container_class' => $this->subnet->isNullRoutesEnabled() ? 'half-section half-section-left' : 'full-section',
			'subnet' => $this->subnet,
			'rdns_records' => $this->rdns_records
		));
	}

	if($this->subnet->isNullRoutesEnabled()) {
		$this->renderTemplate('/subnets/_null_routes.phtml', array(
			'base_url' => $this->base_url,
			'container_class' => $this->subnet->isReverseDnsEnabled() ? 'half-section half-section-right' : 'full-section',
			'subnet' => $this->subnet,
			'null_routes' => $this->null_routes,
			'ip_addresses' => $this->subnet->getIpAddresses()
		));
	}
?>

	<div class="clear"></div>
</div>

<script type="text/javascript">
	$(document).ready(function() {
		$('#contentarea, #content').find('h1').html('ColoCrossing Subnet - <?php echo $this->subnet->getCIDRIpAddress(); ?>');
	});
</script>

<link type="text/css" href="<?php echo WHMCS_BASE_URL; ?>modules/addons/colocrossing/assets/jquery-ui.min.css" rel="stylesheet" />
<script type="text/javascript" src="<?php echo WHMCS_BASE_URL; ?>modules/addons/colocrossing/assets/jquery-ui.min.js"></script>

<style type="text/css">
	div#contentarea h2 { margin-bottom: 10px; }

	div.heading { margin-bottom: 0px; margin-top: 5px; padding: 5px 0px; }
	div.heading h2 { float: left; margin-top: 5px; margin-bottom: 5px !important; }
	div.heading div.actions { float: right; }

	table.datatable { width: 100%; text-align: center; }

	div.full-section { width: 100%; }
	div.half-section { width: 50%; }

	div.half-section-left { float: left; width: 49%; padding-right: 1%; }
	div.half-section-right { float: right; width: 49%; padding-left: 1%; }

	div.half-section table.datatable td, div.half-section table.datatable th{ padding: 3px; }

	div.ui-dialog a.ui-dialog-titlebar-close { display: none; }
</style>
