<div <?php echo isset($container_class) ? 'class="' . $container_class . '"' : ''; ?>>
	<div class="heading">
		<h2>Network Ports</h2>
		<div class="actions">
			<input type="button" class="control-network-ports-button button" data-status="on" value="Turn On" disabled />
			<input type="button" class="control-network-ports-button button" data-status="off" value="Turn Off" disabled />
		</div>
		<div class="clear"></div>
	</div>

	<table class="datatable">
		<tr>
			<th style="width: 60px;">Control</th>
			<th>Device</th>
			<th>Port</th>
			<th>Status</th>
		</tr>
	<?php
		if(count($switches) == 0):
	?>
		<tr>
			<td colspan="4">No network ports configured.</td>
		</tr>
	<?php
		endif;

		foreach ($switches as $i => $switch):
			$switch_id = $switch->getId();
			$switch_owner = $switch->getOwner();
			$switch_url = $module_link . '&controller=devices&action=view&id=' . $switch_id;
			$switch_display = $switch->getName();

			if (isset($switch_owner)) {
				$switch_display = '<a href="' . $switch_url . '">' . $switch_display . '</a>';
			}

			$switch_ports = $switch->getPorts();

			foreach ($switch_ports as $j => $port):
				$port_id = $port->getId();
				$control_status = $port->isControllable() ? '' : 'disabled';
				$control_name = 'switches[' . $switch_id . '][' . $port_id . ']';
	?>
			<tr>
				<td>
					<label style="display: block;">
						<input type="checkbox" name="<?php echo $control_name; ?>" value="<?php echo $port_id; ?>" <?php echo $control_status; ?>/>
					</label>
				</td>
				<td><?php echo $switch_display; ?></td>
				<td><?php echo $port->getDescription(); ?></td>
				<td><?php echo $port->getStatus(); ?></td>
			</tr>
	<?php
			endforeach;
		endforeach;
	?>
	</table>
</div>
