<div <?php echo isset($container_class) ? 'class="' . $container_class . '"' : 'full-section'; ?>>
	<div class="heading">
		<h2>Network Ports</h2>
		<div class="actions">
			<input type="button" class="control-network-ports-button button" data-status="on" value="Turn On" />
			<input type="button" class="control-network-ports-button button" data-status="off" value="Turn Off" />
		</div>
		<div class="clear"></div>
	</div>
	<form id="control-network-ports-form" action="<? echo $module_link . '&controller=devices&action=update-network-ports'; ?>" method="POST">
		<table class="datatable">
			<tr>
				<th style="width: 60px;">Control</th>
				<th>Device</th>
				<th>Port</th>
				<th>Status</th>
				<th>Comment</th>
			</tr>
		<?php
			if(count($switches) == 0):
		?>
			<tr>
				<td colspan="4">No network ports configured.</td>
			</tr>
		<?php
			endif;

			$device_id = $device->getId();

			foreach ($switches as $i => $switch):
				$switch_id = $switch->getId();
				$switch_owner = $switch->getOwner();
				$switch_url = $module_link . '&controller=devices&action=view&id=' . $switch_id;
				$switch_display = $switch->getName();

				if (isset($switch_owner)) {
					$switch_display = '<a href="' . $switch_url . '">' . $switch_display . '</a>';
				}

				$switch_ports = $switch->getPorts();

				foreach ($switch_ports as $j => $port):
					$port_id = $port->getId();
					$port_status = $port->getStatus();
					$port_comment = $port->getComment();

					$control_status = $port->isControllable() ? '' : 'disabled';
					$control_name = 'switches[' . $switch_id . '][' . $port_id . ']';
		?>
				<tr>
					<td>
						<label style="display: block;">
							<input type="checkbox" class="select-port-toggle" name="<?php echo $control_name; ?>"
								   value="<?php echo $device_id; ?>" <?php echo $control_status; ?>/>
						</label>
					</td>
					<td><?php echo $switch_display; ?></td>
					<td><?php echo $port->getDescription(); ?></td>
					<td><?php echo isset($port_status) ? $port_status : 'Unknown'; ?></td>
					<td><?php echo isset($port_comment) ? $port_comment : ''; ?></td>
				</tr>
		<?php
				endforeach;
			endforeach;
		?>
		</table>

		<input type="hidden" name="status" />
		<input type="hidden" name="comment" />
		<input type="hidden" name="origin_device_id" value="<?php echo $device_id; ?>" />
	</form>
</div>

<script type="text/javascript">
	$(document).ready(function() {
		var form = $('#control-network-ports-form'),
		table = form.find('table'),
		button = $('.control-network-ports-button'),
		dialog = $('#control-network-ports-dialog');

		dialog.dialog({
			autoOpen: false,
			width: 310,
			modal: true,
			resizable: false,
			buttons: {
				Confirm: function() {
					var comment = dialog.find('input[name="comment"]').val();

					form.find('input[name="comment"]').val(comment);
					form.submit();
				},
				Cancel: function() {
					dialog.dialog('close');
				}
			}
		});

		button.on('click',function(e) {
			var button = $(this),
			numSelected = table.find('.select-port-toggle:checked').length;

			if(numSelected > 0) {
				form.find('input[name="status"]').val(button.data('status'));
				dialog.find('.status-description').html(button.val().toLowerCase());
				dialog.dialog('open');
			} else {
				alert('Please select one or more network ports to ' + button.val().toLowerCase() + '.');
			}

			e.preventDefault();
			return false;
		});
	});
</script>

<style type="text/css">
	div.field-group { float: left; margin: 5px 0px; }
	div.field-group label { float: left; width: 120px; }
	div.field-group input { float: left; width: 150px; }
</style>

<div id="control-network-ports-dialog" title="Control Network Ports">
	<p>Are you sure you want to <span class="status-description"></span> these network ports?</p>
	<div class="field-group">
		<label>Comment:</label>
		<input type="text" name="comment" maxlength="20"/>
	</div>
</div>