<div data-toggle="tab" id="assets" class="cc-tab-content">
    <div class="row">
        <div class="col30">
            <div class="internalpadding">
                <div class="styled_title"><h2>Assets</h2></div>
                <p>You have the following assets assigned to this device.</p>
            </div>
        </div>
        <div class="col70">
            <div class="internalpadding">
                <table class="table table-striped table-framed table-centered">
                    <thead>
                        <tr>
                            <th>Name</th>
                            <th>Group</th>
                            <th>Quantity</th>
                        </tr>
                    </thead>
                    <tbody>
                    <?php
                        if(count($assets) == 0):
                    ?>
                        <tr>
                            <td class="textcenter" colspan="3">No assets configured to this device.</td>
                        </tr>
                    <?php
                        endif;

                        foreach ($assets as $index => $asset):
                            $groups_names = $asset->getGroupsNames();
                    ?>
                        <tr>
                            <td><?php echo $asset->getName(); ?></td>
                            <td><?php echo implode(', ', $groups_names); ?></td>
                            <td><?php echo $asset->getQuantity(); ?></td>
                        </tr>
                    <?php
                        endforeach;
                    ?>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>
