<div data-toggle="tab" id="bandwidth-usage" class="tab-content">
    <div class="row">
        <div class="col30">
            <div class="internalpadding">
                <div class="styled_title"><h2>Bandwidth Usage</h2></div>
                <p>You have the following bandwidth usage graphs assigned to this device.</p>
            </div>
        </div>
        <div class="col70">
            <div class="internalpadding">

            </div>
        </div>
    </div>
</div>
