<div data-toggle="tab" id="ipmi-controls" class="cc-tab-content">
    <div class="row">
        <div class="col30 col-md-3">
            <div class="internalpadding">
                <div class="styled_title"><h2>IPMI Controls</h2></div>
                <p>Message for status</p>
                <div style="margin-top: 15px;">
                    <input type="button" class="control-power-ports-button btn" data-status="on" value="Lift Null Route" />
                    <input type="button" class="control-power-ports-button btn" data-status="off" value="Renew Lift" />
                    <input type="button" class="control-power-ports-button btn" data-status="restart" value="Replace Null Route" />
                </div>
            </div>
        </div>
    </div>
</div>