<?php
    $control_device_url = ColoCrossing_Utilities::buildUrl($base_url, array(
        'controller' => 'devices',
        'action' => 'update-ipmi'
    ));

    $status = $ipmi_config->getNullRouteStatus()['id'];
    switch($status)
    {
        case 2:
            $lift_expires = $ipmi_config->getNullRouteLiftExpiration();
            $ipmi_message = 'IPMI Null Route has been lifted, and will be automatically replaced at '.date('m/d/Y g:i A', $lift_expires);
            break;
        case 1: 
        case 3:
            $ipmi_message = 'IPMI is currently Null Routed.';
            break;
        default:
            break;
    }

?>


<div data-toggle="tab" id="ipmi-controls" class="cc-tab-content">
    <div class="row">
        <div class="col30 col-md-3">
            <div class="internalpadding">
                <div class="styled_title"><h2>IPMI Controls</h2></div>
            </div>
        </div>
        <div class="col70 col-md-9">
            <strong><? echo $ipmi_message; ?></strong>
            <div style="margin-left: 25px;">
                <?
                    if($status == 1 || $status == 3) {
                ?>
                        <input type="button" class="btn lift_button" data-status="lift" value="Lift Null Route" />
                <?
                    } else if($status == 2) {
                ?>
                        <input type="button" class="btn renew_button" data-status="renew" value="Renew Lift" />
                        <input type="button" class="btn replace_button" data-status="replace" value="Replace Null Route" />
                <?
                    } //end if
                ?>
            </div>
            </div>
        </div>
    </div>

    <form id="control-ipmi-form" action="<?php echo $control_device_url; ?>" method="POST">

        <input type="hidden" name="ipmi_action" />
        <input type="hidden" name="device_id" value="<?php echo $device->getId(); ?>" />
    </form>
</div>

<script type="text/javascript">
    $(document).ready(function() {
        var form = $('#control-ipmi-form'),
        liftButton = $('.lift_button'),
        replaceButton = $('.replace_button'),
        renewButton = $('.renew_button');



        liftButton.on('click', function(e) {
            var button = $(this);
            form.find('input[name="ipmi_action"]').val(button.data('status'));

            if(confirm('Are you sure you want to lift this null route? It will be automatically replaced in 4 hours. The lift may be renewed for a new 4 hour period at any time from this page.')) {
                form.submit();
            }

            e.preventDefault();
            return false;
        });

        replaceButton.on('click', function(e) {
            var button = $(this);
            form.find('input[name="ipmi_action"]').val(button.data('status'));

            if(confirm('Are you sure you want to replace this null route? This will take a few seconds.')) {
                form.submit();
            }

            e.preventDefault();
            return false;
        });


        renewButton.on('click', function(e) {
            var button = $(this);
            form.find('input[name="ipmi_action"]').val(button.data('status'));

            if(confirm('Are you sure you want to renew this lift? The null route will be automatically replaced 4 hours from now.')) {
                form.submit();
            }

            e.preventDefault();
            return false;
        });

    });
</script>
