<div data-toggle="tab" id="network-endpoint-ports" class="tab-content">
    <div class="row">
        <div class="col30">
            <div class="internalpadding">
                <div class="styled_title"><h2>Network Ports</h2></div>
                <p>You have the following network ports assigned to this device.</p>
            </div>
        </div>
        <div class="col70">
            <div class="internalpadding">

            </div>
        </div>
    </div>
</div>
