<div id="overview">
    <div class="row">
        <div class="col30 col-md-3">
            <div class="internalpadding">
                <div class="styled_title"><h2>Information</h2></div>
                <p>Here is an overview of your device.</p>
                <input id="view-service-button" type="button" value="&laquo; Back to Service" class="ui-button btn" style="margin-top: 15px;" />
            </div>
        </div>
        <div class="col70 col-md-9">
            <div class="internalpadding">
            <?php
				if(isset($product) && isset($product_group)):
			?>
            	<p>
                	<strong>Product/Service:</strong>
                	<span><?php echo $product_group->getName() . ' - ' . $product->getName(); ?></span>
                	<span class="label <?php echo strtolower($service->getStatus()); ?>"><?php echo $service->getStatus(); ?></span>
                </p>
            <?php
				endif;
			?>
                <p>
                    <strong>Name:</strong>
                    <span><?php echo $device->getName(); ?>&nbsp;</span>
                </p>
                <p>
                    <strong>Type:</strong>
                    <span><?php echo $type->getName(); ?>&nbsp;</span>
                </p>
                <p>
                    <strong>Nickname:</strong>
                    <span><?php echo $device->getNickname(); ?>&nbsp;</span>
                </p>
                <p>
                    <strong>Hostname:</strong>
                    <span><?php echo $device->getHostname(); ?>&nbsp;</span>
                </p>
                <p>
                    <strong>Zone:</strong>
                    <span><?php echo $device->getSubzone(); ?>&nbsp;</span>
                </p>
                <p>
                    <strong>Rack:</strong>
                    <span>
                    <?php
                    	if($type->isRacked()) {
                    		$rack_name = $device->getRackName();
							echo isset($rack_name) ? $rack_name . ' (U Slot: ' . $device->getUSpace() . ')' : 'Unassigned';
                    	} else {
                    		echo 'Self';
                    	}
                    ?>
                    </span>
                </p>
                <div class="clear"></div>
            </div>
        </div>
    </div>
</div>

<script type="text/javascript">
    $(document).ready(function() {
        $('input#view-service-button').on('click', function(e) {
            window.location = '<?php echo $service_url; ?>';
        });
    });
</script>
