<div data-toggle="tab" id="power-ports" class="tab-content">
    <div class="row">
        <div class="col30">
            <div class="internalpadding">
                <div class="styled_title"><h2>Power Ports</h2></div>
                <p>You have the following power ports assigned to this device.</p>
                <div class="actions" style="margin-top: 15px;">
                    <input type="button" class="control-power-ports-button btn" data-status="on" value="Turn On" />
                    <input type="button" class="control-power-ports-button btn" data-status="off" value="Turn Off" />
                    <input type="button" class="control-power-ports-button btn" data-status="restart" value="Restart" />
                </div>
            </div>
        </div>
        <div class="col70">
            <form id="control-power-ports-form" class="internalpadding" action="<? echo $control_url; ?>" method="POST">
                <table class="table table-striped table-framed table-centered">
                    <thead>
                        <tr>
                            <th style="width: 60px;">Control</th>
                            <th>Device</th>
                            <th>Port</th>
                            <th>Status</th>
                        </tr>
                    </thead>
                    <tbody>
                    <?php
                        if(count($power_distribution_units) == 0):
                    ?>
                        <tr>
                            <td class="textcenter" colspan="3">No power ports configured to this device.</td>
                        </tr>
                    <?php
                        endif;

                        $device_id = $device->getId();

                        foreach ($power_distribution_units as $index => $pdu):
                            $pdu_id = $pdu->getId();
                            $pdu_display = $pdu->getName();
                            $pdu_ports = $pdu->getPorts();

                            foreach ($pdu_ports as $j => $port):
                                $port_id = $port->getId();
                                $port_status = $port->getStatus();

                                $control_status = $port->isControllable() ? '' : 'disabled';
                                $control_name = 'power_distribution_units[' . $pdu_id . '][' . $port_id . ']';

                    ?>
                            <tr>
                                <td>
                                    <label style="display: block;">
                                        <input type="checkbox" class="select-port-toggle" name="<?php echo $control_name; ?>"
                                               value="<?php echo $device_id; ?>" <?php echo $control_status; ?> style="display: inline;" />
                                    </label>
                                </td>
                                <td><?php echo $pdu_display; ?></td>
                                <td><?php echo $port_id; ?></td>
                                <td><?php echo isset($port_status) ? $port_status : 'Unknown'; ?></td>
                            </tr>
                    <?php
                            endforeach;
                        endforeach;
                    ?>
                    </tbody>
                </table>
                <input type="hidden" name="status" />
                <input type="hidden" name="origin_device_id" value="<?php echo $device_id; ?>" />
            </form>
        </div>
    </div>
</div>

<script type="text/javascript">
    $(document).ready(function() {
        var form = $('#control-power-ports-form'),
        table = form.find('table'),
        button = $('.control-power-ports-button');

        button.on('click',function(e) {
            var button = $(this),
            numSelected = table.find('.select-port-toggle:checked').length;

            if(numSelected === 0) {
                alert('Please select one or more power ports to ' + button.val().toLowerCase() + '.');
            } else if (confirm('Are you sure you want to ' + button.val().toLowerCase() + ' these ports?')) {
                form.find('input[name="status"]').val(button.data('status'));
                form.submit();
            }

            e.preventDefault();
            return false;
        });
    });
</script>
