<div data-toggle="tab" id="power-ports" class="tab-content">
    <div class="row">
        <div class="col30">
            <div class="internalpadding">
                <div class="styled_title"><h2>Power Ports</h2></div>
                <p>You have the following power port configuration for this device.</p>
            </div>
        </div>
        <div class="col70">
            <div class="internalpadding">

            </div>
        </div>
    </div>
</div>
