<div data-toggle="tab" id="racked-devices" class="tab-content">
    <div class="row">
        <div class="col30">
            <div class="internalpadding">
                <div class="styled_title"><h2>Racked Devices</h2></div>
                <p>You have the following devices in this rack.</p>
            </div>
        </div>
        <div class="col70">
            <div class="internalpadding">

            </div>
        </div>
    </div>
</div>
