<div data-toggle="tab" id="racked-devices" class="cc-tab-content">
    <div class="row">
        <div class="col30">
            <div class="internalpadding">
                <div class="styled_title"><h2>Racked Devices</h2></div>
                <p>You have the following devices in this rack.</p>
            </div>
        </div>
        <div class="col70">
            <div class="internalpadding">
                <table class="table table-striped table-framed table-centered">
                    <thead>
                        <tr>
                            <th>Name</th>
                            <th>Nickname</th>
                            <th>Type</th>
                            <th>Hostname</th>
                        </tr>
                    </thead>
                    <tbody>
                    <?php
                        if(count($devices) == 0):
                    ?>
                        <tr>
                            <td colspan="4">No devices configured.</td>
                        </tr>
                    <?php
                        endif;

                        foreach ($devices as $i => $device):
                            $type = $device->getType();

                            $device_id = $device->getId();
                            $device_name = $device->getName();

                            $service = ColoCrossing_Model_Service::findByDevice($device_id);

                            if(isset($service) && $service->isAssignedToUser($current_user) && $service->isActive()) {
                                $device_url = ColoCrossing_Utilities::buildUrl($base_url, array(
                                    'controller' => 'devices',
                                    'action' => 'view',
                                    'id' => $device_id
                                ));
                                $device_name = '<a href="' . $device_url . '">' . $device_name . '</a>';
                            }
                    ?>
                        <tr>
                            <td><?php echo $device_name; ?></td>
                            <td><?php echo $device->getNickname(); ?></td>
                            <td><?php echo $type->getName(); ?></td>
                            <td><?php echo $device->getHostname(); ?></td>
                        </tr>
                    <?php
                        endforeach;
                    ?>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>
