<div data-toggle="tab" id="subnets" class="cc-tab-content">
    <div class="row">
        <div class="col30">
            <div class="internalpadding">
                <div class="styled_title"><h2>Subnets</h2></div>
                <p>You have the following subnets assigned to this device.</p>
            </div>
        </div>
        <div class="col70">
            <div class="internalpadding">
                <table class="table table-striped table-framed table-centered">
                    <thead>
                        <tr>
                            <th>IP Address</th>
                            <th>SWIP</th>
                        </tr>
                    </thead>
                    <tbody>
					<?php
						if(count($subnets) == 0):
					?>
						<tr>
							<td class="textcenter" colspan="2">No subnets configured to this device.</td>
						</tr>
					<?php
						endif;

						foreach ($subnets as $index => $subnet):
                            $id = $subnet->getId();
                            $url = ColoCrossing_Utilities::buildUrl($base_url, array(
                                'controller' => 'subnets',
                                'action' => 'view',
                                 'id' => $id
                            ));
					?>
						<tr>
							<td><a href="<?php echo $url; ?>"><?php echo $subnet->getCIDRIpAddress(); ?></a></td>
							<td><?php echo $subnet->isSwip() ? 'Yes' : 'No'; ?></td>
						</tr>
					<?php
						endforeach;
					?>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>
