<?php
	$title = $this->device->getName();

	if(isset($this->product)) {
		$title = $this->product->getName() . ' - ' . $title;
	}
?>

<div class="page-header">
    <div class="styled_title"><h1><?php echo $title; ?></h1></div>
</div>

<?php
	$this->renderFlashMessage();
?>

<div id="device_tabs">
    <ul class="nav nav-tabs tabs">
    	<?php
        echo '<li><a href="#device_info">Information</a></li>';
        echo '<li><a href="#device_assets">Assets</a></li>';

        if($this->type->isNetworked() || $this->type->isVirtual()) {
        	echo '<li><a href="#device_subnets">Subnets</a></li>';
        }

        if($this->type->isPowerEndpoint()) {
			echo '<li><a href="#device_power">Power Ports</a></li>';
		} else if($this->type->isPowerDistribution()) {
			echo '<li><a href="#device_power">Power Ports</a></li>';
		}

		if($this->type->isNetworkEndpoint()) {
			echo '<li><a href="#device_network">Network Ports</a></li>';
		} else if($this->type->isNetworkDistribution()) {
			echo '<li><a href="#device_network">Network Ports</a></li>';
		}

		if($this->type->isRack()) {
			echo '<li><a href="#racked_device">Racked Devices</a></li>';
		}
        
        if($this->type->isNetworkEndpoint() && count($this->bandwidth_graphs)) {
			echo '<li><a href="#device_bandwidth">Bandwidth Usage</a></li>';
		}
        
        $ipmi_config = $this->device->getIpmiConfiguration();
		$ipmi_null_route = $ipmi_config->getNullRoute();
		$ipmi_null_status = $ipmi_config->getNullRouteStatus()['id'];
		if(isset($ipmi_null_route) && $ipmi_null_status != 4)
		{
			echo '<li><a href="#device_ipmi">IPMI Controls</a></li>';
		}
		?>
    </ul>

    <div class="main_content">
    
        <div id="device_info">
        <?php
            $this->renderTemplate('/devices/_overview.phtml', array(
    		'device' => $this->device,
    		'type' => $this->type,
    		'service' => $this->service,
    		'service_url' => ColoCrossing_Utilities::buildUrl(WHMCS_BASE_URL . 'clientarea.php', array(
    			'action' => 'productdetails',
    			'id' => $this->service->getId()
    		)),
    		'product' => $this->product,
    		'product_group' => $this->product_group
    	));
        ?>
        </div>
        <div id="device_assets">
        <?php
        	$this->renderTemplate('/devices/_assets.phtml', array(
        		'assets' => $this->assets,
        	));
        ?>
        </div>
        <div id="device_subnets">
        <?php
        	if($this->type->isNetworked() || $this->type->isVirtual()) {
        		$this->renderTemplate('/devices/_subnets.phtml', array(
        			'base_url' => $this->base_url,
        			'subnets' => $this->subnets
        		));
        	}
        ?>
        </div>
        <div id="device_power">
        <?php
        	if($this->type->isPowerEndpoint()) {
        		$this->renderTemplate('/devices/_power_endpoint_ports.phtml', array(
        			'control_url' => ColoCrossing_Utilities::buildUrl($this->base_url, array(
        				'controller' => 'devices',
        				'action' => 'update-power-ports'
        			)),
        			'device' => $this->device,
        			'power_distribution_units' => $this->power_distribution_units
        		));
        	} else if($this->type->isPowerDistribution()) {
        		$this->renderTemplate('/devices/_power_distribution_ports.phtml', array(
        			'base_url' => $this->base_url,
        			'current_user' => $this->current_user,
        			'control_url' => ColoCrossing_Utilities::buildUrl($this->base_url, array(
        				'controller' => 'devices',
        				'action' => 'update-power-ports'
        			)),
        			'pdu' => $this->device
        		));
        	}
        ?>
        </div>
        <div id="device_network">
        <?php
        	if($this->type->isNetworkEndpoint()) {
        		$this->renderTemplate('/devices/_network_endpoint_ports.phtml', array(
        			'control_url' => ColoCrossing_Utilities::buildUrl($this->base_url, array(
        				'controller' => 'devices',
        				'action' => 'update-network-ports'
        			)),
        			'device' => $this->device,
        			'switches' => $this->switches
        		));
        	} else if($this->type->isNetworkDistribution()) {
        		$this->renderTemplate('/devices/_network_distribution_ports.phtml', array(
        			'base_url' => $this->base_url,
        			'current_user' => $this->current_user,
        			'control_url' => ColoCrossing_Utilities::buildUrl($this->base_url, array(
        				'controller' => 'devices',
        				'action' => 'update-network-ports'
        			)),
        			'switch' => $this->device
        		));
        	}
        ?>
        </div>
	    <div id="racked_device">
        <?php
        	if($this->type->isRack()) {
				$this->renderTemplate('/devices/_racked_devices.phtml', array(
					'base_url' => $this->base_url,
					'current_user' => $this->current_user,
					'devices' => $this->devices
				));
			}
        ?>
        </div>
        <div id="device_bandwidth">
        <?php
        	if($this->type->isNetworkEndpoint() && count($this->bandwidth_graphs)) {
        		$this->renderTemplate('/devices/_bandwidth_usage.phtml', array(
        			'bandwidth_graph_url' => ColoCrossing_Utilities::buildUrl($this->base_url, array(
        				'controller' => 'devices',
        				'action' => 'bandwidth-graph'
        			)),
        			'bandwidth_graphs' => $this->bandwidth_graphs,
        			'bandwidth_graph_durations' => $this->bandwidth_graph_durations
        		));
        	}
        ?>
        </div>
        <div id="device_ipmi">
        <?php
        	if(isset($ipmi_null_route) && $ipmi_null_status != 4)
        	{
        		$this->renderTemplate('/devices/_ipmi_controls.phtml', array(
        			'control_url' => ColoCrossing_Utilities::buildUrl($this->base_url, array(
        				'controller' => 'devices',
        				'action' => 'update-ipmi'
        			)),
        			'ipmi_config' => $ipmi_config,
        			'ipmi_null_route' => $ipmi_null_route,
        			'current_user' => $this->current_user,
        			'device' => $this->device,
        		));
        	}
        ?>
        </div>
    </div>
</div>

<link type="text/css" href="<?php echo WHMCS_BASE_URL; ?>modules/addons/colocrossing/assets/jquery-ui.min.css" rel="stylesheet" />
<script type="text/javascript" src="<?php echo WHMCS_BASE_URL; ?>modules/addons/colocrossing/assets/jquery-ui.min.js"></script>

<script type="text/javascript">
    $(document).ready(function() {
        $('#device_tabs').tabs({cookie: {name: 'api-tabs', expires: 7 }});
    });
</script>
