<?php
	$assign_devices_url = ColoCrossing_Utilities::buildUrl($this->base_url, array(
		'controller' => 'services',
		'action' => 'assign-devices'
	));
	$current_url = ColoCrossing_Utilities::buildUrl($this->base_url, array(
		'controller' => 'services',
		'action' => 'index',
		'page_size' => $this->page_size
	));
?>
<form id="assign-devices-form" method="POST" action="<?php echo $assign_devices_url; ?>">
	<div style="float: right;">
		<input id="assign-devices-button" type="submit" value="Assign Devices" class="btn-small" />
	</div>
	<h1>Unassigned ColoCrossing Services</h1>

	<table width="100%" border="0" cellpadding="3" cellspacing="0">
		<tr>
			<td width="50%" align="left"><?php echo $this->record_count . ' Records Found, Page ' . $this->page_number . ' of ' . $this->page_count ?></td>
			<td width="50%" align="right">
				<label>Jump to Page:</label>
				<select id='page-select'>
				<?php
					for ($page = 1; $page <= $this->page_count; $page++) {
						echo '<option value="' . $page . '" ' . ($this->page_number == $page ? 'selected' : null) . '>' . $page . '</option>';
					}
				?>
				</select>
				<input id='page-select-button' type="submit" value="Go" class="btn-small">
			</td>
		</tr>
	</table>

<?php
	$this->renderFlashMessage();
?>

	<div id="duplicate-assignment-error" style="display: none;">
	<?php
		$this->renderTemplate('/flash-messages/error.phtml', array(
			'content' => 'A device can be assigned to only one service at a time. Please verify you are assigning each device only once.'
		));
	?>
	</div>

	<div class="tablebg">
		<table class="datatable" width="100%" border="0" cellspacing="1" cellpadding="3" style="text-align: center;">
			<tr>
				<th style="width: 60px;">Assign</th>
				<th>Product/Service</th>
				<th>Client</th>
				<th>Status</th>
				<th>Hostname</th>
				<th>Device</th>
			</tr>
		<?php
			if(count($this->services) == 0):
		?>
			<tr>
				<td colspan="6">No unassigned services with matching hostnames found.</td>
			</tr>
		<?php
			endif;

			foreach ($this->services as $i => $service):
				$service_id = $service->getId();
				$service_url = ColoCrossing_Utilities::buildUrl('clientsservices.php', array(
					'id' => $service_id
				));
				$service_hostname = $service->getHostname();

				$possible_devices = isset($this->devices_by_hostname[$service_hostname]) ? $this->devices_by_hostname[$service_hostname] : array();

				$product = $service->getProduct();
				$product_group = empty($product) ? null : $product->getGroup();
				$product_name = isset($product) && isset($product_group) ? $product_group->getName() . ' - ' . $product->getName() : 'Unassigned';

				$client = $service->getClient();
				$client_name = isset($client) ? $client->getFullName() : 'Unassigned';

				if(isset($client)) {
					$client_url = ColoCrossing_Utilities::buildUrl('clientssummary.php', array(
						'userid' => $client->getId()
					));
					$client_name = '<a href="' . $client_url . '">' . $client_name . '</a>';
				}

				$select_status = count($possible_devices) ? 'disabled' : '';
		?>
			<tr class="service-row">
				<td>
				<?php
					if(count($possible_devices)):
				?>
					<label style="display: block;">
						<input class="service-input" type="checkbox" name="services[]" value="<?php echo $service_id; ?>" />
					</label>
				<?php
					endif;
				?>
				</td>
				<td><a href="<?php echo $service_url; ?>"><?php echo $product_name; ?></a></td>
				<td><?php echo $client_name; ?></td>
				<td><?php echo $service->getStatus(); ?></td>
				<td><?php echo $service_hostname; ?></td>
				<td>
				<?php
					if(empty($possible_devices)):
						echo 'Unassigned';
					elseif(count($possible_devices) == 1):
						$device = $possible_devices[0];
						$device_id = $device->getId();
						$device_url = ColoCrossing_Utilities::buildUrl($this->base_url, array(
							'controller' => 'devices',
							'action' => 'view',
							'id' => $device_id
						));
				?>
					<a href="<?php echo $device_url; ?>"><?php echo $device->getName(); ?></a>
					<input class="device-input" type="hidden" name="devices[<?php echo $service_id; ?>]" value="<?php echo $device_id; ?>" />
				<?php
					else:
				?>
					<select class="device-input" name="devices[<?php echo $service_id; ?>]">
					<?php
						foreach ($possible_devices as $j => $device) {
							echo '<option value="' . $device->getId() . '">' . $device->getName() . '</option>';
						}
					?>
					</select>
				<?php
					endif;
				?>
				</td>
			</tr>
		<?php
			endforeach;
		?>
		</table>
	</div>

	<p align="center">
	<?php
		if($this->page_number > 1) {
			$page_url = ColoCrossing_Utilities::buildUrl($current_url, array('page' => $this->page_number - 1));
			echo '<a href="' . $page_url . '">&laquo; Previous Page</a>';
		} else {
			echo '<span id="previous-page-button">&laquo; Previous Page</span>';
		}

		echo '&nbsp;';

		if($this->page_number < $this->page_count) {
			$page_url = ColoCrossing_Utilities::buildUrl($current_url, array('page' => $this->page_number + 1));
			echo '<a href="' . $page_url . '">Next Page &raquo;</a>';
		} else {
			echo '<span id="next-page-button">Next Page &raquo;</span>';
		}
	?>
	</p>
</form>

<script type="text/javascript">

	$(document).ready(function() {

		$('#contentarea, #content').find('h1').first().remove();

		$('#assign-devices-button').on('click', function(e) {
			var devices = {},
			validAssignments = true;

			$('tr.service-row').each(function() {
				var row = $(this),
				serviceInput = row.find('.service-input'),
				deviceInput = row.find('.device-input');

				if(serviceInput.prop('disabled') || !serviceInput.prop('checked')) {
					return;
				}

				if(devices[deviceInput.val()]) {
					validAssignments = false;
				}

				devices[deviceInput.val()] = true;
			});

			$('#duplicate-assignment-error').hide();

			if(!validAssignments) {
				$('#duplicate-assignment-error').show();
			} else if(confirm('Are you sure you want to assign these devices to the selected services?')) {
				$('#assign-devices-button').prop('disabled', true);
				$('#assign-devices-form').submit();
			}

			e.preventDefault();
			return false;
		});

		$('select#page-select').on('change', function() {
			var url = '<?php echo $current_url; ?>',
			page = $(this).val();

			window.location = url + '&page=' + page;
		});

		$('input#page-select-button').on('click', function(e) {
			$('select#page-select').trigger('change');

			e.preventDefault();
			return false;
		});



	});

</script>

<style type="text/css">
	div#contentarea h1 { margin-bottom: 10px; }
</style>
