<?php
	$this->renderFlashMessage();

	if(empty($this->message)) {
		$this->message = 'An error occured while trying to load this page. Please try again later.';
	}

	echo '<p>' . $this->message . '</p>';
?>

<script type="text/javascript">

	$(document).ready(function() {

		$('#contentarea, #content').find('h1').html('ColoCrossing - An Error Has Occurred!');

	});

</script>

<style type="text/css">
	div#contentarea h1 { margin-bottom: 10px; }
</style>