<?php

/**
 * An Exception For Errors Generated By the API
 * @category   ColoCrossing
 * @package    ColoCrossing_Error
 */
class ColoCrossing_Error_Api extends ColoCrossing_Error
{

	/**
	 * The HTTP Status Returned
	 * @var int
	 */
	private $status;

	/**
	 * @param int $status  		The Http Status of the Request.
	 * @param array   $content 	The content returned from the API.
	 * @param string $message 	Optional. Defaults to "ColoCrossing API Error - Message From API"
	 */
	public function __construct($status = 500, array $content = array(), $message = null)
	{
		parent::__construct((isset($message) ? $message : 'ColoCrossing API Error') . ' - ' . $content['message'], $content['type']);

		$this->status = $status;
	}

	/**
	 * @return string The Http Status
	 */
	public function getStatus()
	{
		return $this->status;
	}

}
