<div data-toggle="tab" id="overview" class="tab-content">
    <div class="row">
        <div class="col30">
            <div class="internalpadding">
                <div class="styled_title"><h2>Information</h2></div>
                <p>Here is an overview of your subnet.</p>
                <input id="view-device-button" type="button" value="&laquo; Back to Device" class="btn" style="margin-top: 15px;" />
            </div>
        </div>
        <div class="col70">
            <div class="internalpadding">
            	<div class="col2half">
                    <h4>IP Address:</h4>
                    <span><?php echo $subnet->getCIDRIpAddress(); ?>&nbsp;</span>
                </div>
                <div class="col2half">
                    <h4>SWIP:</h4>
                    <span><?php echo $subnet->isSwip() ? 'Yes' : 'No'; ?>&nbsp;</span>
                </div>
                <div class="col2half">
                    <h4>Usable Addresses:</h4>
                    <span><?php echo $subnet->getNumberOfUsableIpAddresses(); ?>&nbsp;</span>
                </div>
                <div class="col2half">
                    <h4>Total Addresses:</h4>
                    <span><?php echo $subnet->getNumberOfIpAddresses(); ?>&nbsp;</span>
                </div>
            <?php
            	if(count($ip_addresses) > 1):
            ?>
                <div class="col2half">
                    <h4>Start IP Address:</h4>
                    <span><?php echo $ip_addresses[0]; ?>&nbsp;</span>
                </div>
                <div class="col2half">
                    <h4>End IP Address:</h4>
                    <span><?php echo $ip_addresses[count($ip_addresses) - 1]; ?>&nbsp;</span>
                </div>
            <?php
            	endif;
            ?>
            	<div class="col2half">
                    <h4>Device:</h4>
                    <a href="<?php echo $device_url; ?>"><?php echo $device->getName(); ?>&nbsp;</a>
                </div>
                <div class="col2half">
                    <h4>Zone:</h4>
                    <span><?php echo $subnet->getSubzone(); ?>&nbsp;</span>
                </div>
                <div class="clear"></div>
            </div>
        </div>
    </div>
</div>

<script type="text/javascript">
    $(document).ready(function() {
        $('input#view-device-button').on('click', function(e) {
            window.location = '<?php echo $device_url; ?>';
        });
    });
</script>
