<div data-toggle="tab" id="rdns-records" class="tab-content">
    <div class="row">
        <div class="col30">
            <div class="internalpadding">
                <div class="styled_title"><h2>Reverse DNS Records</h2></div>
                <p>You have the following reverse DNS records for this subnet.</p>
            </div>
        </div>
        <div class="col70">
            <div class="internalpadding">

            </div>
        </div>
    </div>
</div>
