<div class="page-header">
    <div class="styled_title"><h1><?php echo $this->subnet->getCIDRIpAddress(); ?></h1></div>
</div>

<?php
	$this->renderFlashMessage();
?>

<div id="subnet_tabs">
    <ul class="nav nav-tabs tabs">
	<?php
	echo '<li><a href="#subnet_overview">Information</a></li>';

	if($this->subnet->isReverseDnsEnabled()) {
		echo '<li><a href="#rdns_records">Reverse DNS Records</a></li>';
	}

	if($this->subnet->isNullRoutesEnabled()) {
		echo '<li><a href="#null_routes">Null Routes</a></li>';
	}
    ?>
	</ul>
    <div class="main_content">
        <div id="subnet_overview">
        <?php
            $this->renderTemplate('/subnets/_overview.phtml', array(
				'subnet' => $this->subnet,
				'device' => $this->device,
				'device_url' => ColoCrossing_Utilities::buildUrl($this->base_url, array(
					'controller' => 'devices',
					'action' => 'view',
					'id' => $this->device->getId()
				)),
				'ip_addresses' => $this->ip_addresses
			));
        ?>
        </div>
        <div id="rdns_records">
        <?php
        	if($this->subnet->isReverseDnsEnabled()) {
				$this->renderTemplate('/subnets/_rdns_records.phtml', array(
					'update_rdns_url' => ColoCrossing_Utilities::buildUrl($this->base_url, array(
						'controller' => 'subnets',
						'action' => 'update',
						'id' => $this->subnet->getId()
					)),
					'rdns_records' => $this->rdns_records,
					'pending_service_request' => $this->subnet->isPendingServiceRequest()
				));
			}
        ?>
        </div>
        <div id="null_routes">
        <?php
        	if($this->subnet->isNullRoutesEnabled()) {
				$this->renderTemplate('/subnets/_null_routes.phtml', array(
					'add_null_route_url' => ColoCrossing_Utilities::buildUrl($this->base_url, array(
						'controller' => 'null-routes',
						'action' => 'create',
						'subnet_id' => $this->subnet->getId()
					)),
					'remove_null_route_url' => ColoCrossing_Utilities::buildUrl($this->base_url, array(
						'controller' => 'null-routes',
						'action' => 'destroy'
					)),
					'null_routes' => $this->null_routes,
					'ip_addresses' => $this->ip_addresses
				));
			}
        ?>
        </div>
    </div>
</div>

<link type="text/css" href="<?php echo WHMCS_BASE_URL; ?>modules/addons/colocrossing/assets/jquery-ui.min.css" rel="stylesheet" />
<script type="text/javascript" src="<?php echo WHMCS_BASE_URL; ?>modules/addons/colocrossing/assets/jquery-ui.min.js"></script>

<script type="text/javascript">
    $(document).ready(function() {
        $('#subnet_tabs').tabs({cookie: {name: 'subnet-tabs', expires: 7 }});
    });
</script>