<?php
	$columns = array(
		'device_name' => 'Device',
		'total_usage' => 'Total Usage',
		'ninety_fifth_usage' => '95th Percentile Usage',
		'start_date' => 'Metering Start',
		'end_date' => 'Metering End'
	);
	$sortable_columns = array('device_name', 'total_usage', 'ninety_fifth_usage');
?>

<form id="bandwidth-usages-table-form" method="get">
	<h1>ColoCrossing Bandwidth Usages</h1>

<?php
	$this->renderFlashMessage();
?>

	<table width="100%" border="0" cellpadding="3" cellspacing="0">
		<tr>
			<td width="50%" align="left"><?php echo $this->num_records . ' Records Found, Page ' . $this->page . ' of ' . $this->num_pages ?></td>
			<td width="50%" align="right">
				<label>Jump to Page:</label>
				<select id='page-select'>
				<?php
					for ($page = 1; $page <= $this->num_pages; $page++) {
						echo '<option value="' . $page . '" ' . ($this->page == $page ? 'selected' : null) . '>' . $page . '</option>';
					}
				?>
				</select>
				<input type="submit" value="Go" class="btn-small">
			</td>
		</tr>
	</table>

	<div class="tablebg">
		<table class="datatable" width="100%" border="0" cellspacing="1" cellpadding="3" style="text-align: center;">
			<tr>
			<?php
				foreach ($columns as $id => $name) {
					if(in_array($id, $sortable_columns)) {
						$image = $this->sort == $id ? '<img src="images/' . $this->order . '.gif" class="absmiddle">' : '';
						echo '<th><a class="sort-column-button" href="#sort" data-sort="' . $id . '">' . $name . '</a> ' . $image . '</th>';
					} else {
						echo '<th>' . $name . '</th>';
					}
				}
			?>
			</tr>
		<?php
			if(count($this->bandwidth_usages) == 0):
		?>
			<tr>
				<td colspan="5">No devices with metering found.</td>
			</tr>
		<?php
			endif;

			foreach ($this->bandwidth_usages as $bandwidth_usage):
				$device_id = $bandwidth_usage->getDeviceId();
				$device_name = $bandwidth_usage->getDeviceName();
				$device_url = ColoCrossing_Utilities::buildUrl($this->base_url, array(
					'controller' => 'devices',
					'action' => 'view',
					'id' => $device_id
				));

				$start = $bandwidth_usage->getStartDate();
				$start = isset($start) ? date('m/d/Y', $start) : 'Unknown';

				$end = $bandwidth_usage->getEndDate();
				$end = isset($end) ? date('m/d/Y', $end) : 'Unknown';
		?>
			<tr>
				<td><a href="<?php echo $device_url; ?>"><?php echo $device_name; ?></a></td>
				<td><?php echo $bandwidth_usage->getTotalUsage(); ?> GB</td>
				<td><?php echo $bandwidth_usage->getNinetyFifthUsage(); ?> mbit</td>
				<td><?php echo $start; ?></td>
				<td><?php echo $end; ?></td>
			</tr>
		<?php
			endforeach;
		?>
		</table>
	</div>

	<p align="center">
	<?php
		if($this->page > 1) {
			echo '<a id="previous-page-button" href="#previous-page">&laquo; Previous Page</a>';
		} else {
			echo '<span id="previous-page-button">&laquo; Previous Page</span>';
		}

		echo '&nbsp;';

		if($this->page < $this->num_pages) {
			echo '<a id="next-page-button" href="#next-page">Next Page &raquo;</a>';
		} else {
			echo '<span id="next-page-button">Next Page &raquo;</span>';
		}
	?>
	</p>

	<input type="hidden" name="module" value="colocrossing" />
	<input type="hidden" name="controller" value="bandwidth-usages" />
	<input type="hidden" name="action" value="index" />
	<input type="hidden" name="sort" value="<?php echo $this->sort; ?>" />
	<input type="hidden" name="order" value="<?php echo $this->order; ?>" />
	<input type="hidden" name="page" value="<?php echo $this->page; ?>" />
</form>

<script type="text/javascript">

	$(document).ready(function() {

		$('#contentarea, #content').find('h1').first().remove();

		var currentPage = parseInt('<?php echo $this->page; ?>'),
		form = $('#bandwidth-usages-table-form'),
		sortInput = form.find('input[name="sort"]'),
		orderInput = form.find('input[name="order"]'),
		pageInput = form.find('input[name="page"]');

		form.find('a.sort-column-button').on('click', function(e) {
			var button = $(this);

			if(button.data('sort') == sortInput.val()) {
				orderInput.val(orderInput.val() == 'asc' ? 'desc' : 'asc');
			} else {
				sortInput.val(button.data('sort'));
				orderInput.val('asc');
			}

			form.submit();

			e.preventDefault();
			return false;
		});

		form.find('a#previous-page-button').on('click', function(e) {
			pageInput.val(currentPage - 1);
			form.submit();

			e.preventDefault();
			return false;
		});

		form.find('a#next-page-button').on('click', function(e) {
			pageInput.val(currentPage + 1);
			form.submit();

			e.preventDefault();
			return false;
		});

		form.find('select#page-select').on('change', function() {
			pageInput.val($(this).val());
			form.submit();

			e.preventDefault();
			return false;
		});

	});

</script>

<style type="text/css">
	div#contentarea h1 { margin-bottom: 10px; }
</style>
