<?php
	$device_url = ColoCrossing_Utilities::buildUrl($this->base_url, array(
        'controller' => 'devices',
        'action' => 'view',
        'id' => $this->device->getId()
    ));
    $network_control_url = ColoCrossing_Utilities::buildUrl($this->base_url, array(
        'controller' => 'services',
        'action' => 'control-device-network',
        'id' => $this->service->getId()
    ));
    $power_control_url = ColoCrossing_Utilities::buildUrl($this->base_url, array(
        'controller' => 'services',
        'action' => 'control-device-power',
        'id' => $this->service->getId()
    ));
?>

<div id="colocrossing-flash-message">
<?php
	$this->renderFlashMessage();
?>
</div>

<div id="colocrossing-module">
	<div class="row" style="padding-bottom: 0px;">
	    <div class="col-sm-5 text-right">
	        <strong>Device</strong>
	    </div>
	    <div class="col-sm-7 text-left">
	        <a href="<?php echo $device_url; ?>"><?php echo $this->device->getName(); ?></a>
	    </div>
	</div>
</div>

<?php
	if($this->type->isPowerEndpoint() || $this->type->isNetworkEndpoint()):
?>
	<h3 style="text-align: left; margin-bottom: 10px;">Ports</h3>
	<table class="table table-bordered table-striped" style="width: 100%;">
	<?php
		if($this->type->isPowerEndpoint() && isset($this->power_status)):
	?>
		<tr>
			<td style="width: 25%;">Power Status</td>
			<td style="width: 75%;">
				<strong style="color: <?php echo $this->power_status_color; ?>;"><?php echo $this->power_status; ?></strong>
				<?php
					if($this->power_status == 'Mixed') {
						echo '<a href="' . $device_url . '#power-ports">(Details)</a>';
					}
				?>
			</td>
		</tr>
		<?php
			if($this->is_power_controllable):
		?>
			<tr>
				<td style="width: 25%;">Power Control</td>
				<td style="width: 75%;">
					<button class="power-control-btn btn btn-success success" data-status="on">Turn On</button>
					<button class="power-control-btn btn btn-danger danger" data-status="off">Turn Off</button>
					<button class="power-control-btn btn btn-primary primary" data-status="restart">Restart</button>
				</td>
			</tr>
	<?php
			endif;
		endif;

		if($this->type->isNetworkEndpoint() && isset($this->network_status)):
	?>
		<tr>
			<td style="width: 25%;">Network Status</td>
			<td style="width: 75%;">
				<strong style="color: <?php echo $this->network_status_color; ?>;"><?php echo $this->network_status; ?></strong>
				<?php
					if($this->network_status == 'Mixed') {
						echo '<a href="' . $device_url . '#network-ports">(Details)</a>';
					}
				?>
			</td>
		</tr>
		<?php
			if($this->is_network_controllable):
		?>
			<tr>
				<td style="width: 25%;">Network Control</td>
				<td style="width: 75%;">
					<button class="network-control-btn btn btn-success success" data-status="on">Turn On</button>
					<button class="network-control-btn btn btn-danger danger" data-status="off">Turn Off</button>
				</td>
			</tr>
	<?php
			endif;
		endif;
	?>
	</table>
<?php
	endif;

	if(isset($this->subnets)):
?>

	<h3 style="text-align: left; margin-bottom: 10px;">IP Allocations</h3>
	<table class="table table-bordered table-striped" style="width: 100%;">
		<thead>
	        <tr>
	            <th>Subnet</th>
	            <th>First Usable IP</th>
	            <th>Last Usable IP</th>
	            <th style="width: 125px"></th>
	        </tr>
	    </thead>
	    <tbody>
		<?php
			if(count($this->subnets) == 0):
		?>
			<tr>
				<td class="textcenter" colspan="3">No IP addresses allocated to this device.</td>
			</tr>
		<?php
			endif;

			foreach ($this->subnets as $index => $subnet):
				$subnet_url = ColoCrossing_Utilities::buildUrl($this->base_url, array(
			        'controller' => 'subnets',
			        'action' => 'view',
			        'id' => $subnet->getId()
			    ));
		?>
			<tr>
				<td><a href="<?php echo $subnet_url; ?>"><?php echo $subnet->getCIDRIpAddress(); ?></a></td>
				<td><?php echo $subnet->getFirstUsableIpAddress(); ?></td>
				<td><?php echo $subnet->getLastUsableIpAddress(); ?></td>
				<td style="text-align: center;"><a class="btn" href="<?php echo $subnet_url; ?>"><i class="icon icon-list-alt"></i> View Details</a></td>
			</tr>
		<?php
			endforeach;
		?>
	    </tbody>
	</table>
<?php
	endif;

	if($this->type->isNetworkEndpoint() && count($this->bandwidth_graphs)):
?>
	<h3 style="text-align: left; margin-bottom: 10px;">Graphs</h3>
	<?php
		foreach ($this->bandwidth_graphs as $index => $graph) {
			$graph_url = ColoCrossing_Utilities::buildUrl($this->base_url, array(
		        'controller' => 'devices',
		        'action' => 'bandwidth-graph',
		        'id' => $this->device->getId(),
		        'switch_id' => $graph['switch_id'],
		        'port_id' => $graph['port_id'],
		        'duration' => '1 hour'
		    ));
		    echo '<img src="' . $graph_url . '" style="width: 100%; margin-bottom: 10px;">';
		}
	?>
<?php
	endif;
?>


<script type="text/javascript">
	$(document).ready(function() {
		//Move Module Content To Top of Page and Delete Container
		var module = $('#colocrossing-module'),
		moduleContainer = module.parent(),
		infoContainer = moduleContainer.parent(),
		flashMessage = $('#colocrossing-flash-message'),
		tabs = $('#tabs');

		infoContainer.prepend(module);
		tabs.before(flashMessage);

		$('button.power-control-btn').on('click', function(e) {
			var button = $(this),
			action = button.html().toLowerCase(),
			status = button.data('status');

			if(confirm('Are you sure you want to ' + action + ' the power for this device?')) {
				$('form#control-power-form').find('input[name="status"]').val(status);
				$('form#control-power-form').submit();
			}

			e.preventDefault();
			return false;
		});

		$('button.network-control-btn').on('click', function(e) {
			var button = $(this),
			action = button.html().toLowerCase(),
			status = button.data('status');

			if(confirm('Are you sure you want to ' + action + ' the network for this device?')) {
				$('form#control-network-form').find('input[name="status"]').val(status);
				$('form#control-network-form').submit();
			}

			e.preventDefault();
			return false;
		});
	});
</script>

<style type="text/css">
	.moduleoutput { border: none !important; padding: 0px !important; }
</style>

<form id="control-power-form" action="<?php echo $power_control_url; ?>" method="POST">
	<input type="hidden" name="status" />
</form>

<form id="control-network-form" action="<?php echo $network_control_url; ?>" method="POST">
	<input type="hidden" name="status" />
</form>
