<?php
	$control_device_url = ColoCrossing_Utilities::buildUrl($base_url, array(
		'controller' => 'devices',
		'action' => 'update-ipmi'
	));

	$status = $ipmi_config->getNullRouteStatus()['id'];
	switch($status)
	{
		case 2:
			$lift_expires = $ipmi_config->getNullRouteLiftExpiration();
			$ipmi_message = 'IPMI Null Route has been lifted, and will be automatically replaced at '.date('m/d/Y g:i A', $lift_expires);
			break;
		case 1:	
		case 3:
			$ipmi_message = 'IPMI is currently Null Routed.';
			break;
		default:
			break;
	}

?>

<div <?php echo isset($container_class) ? 'class="' . $container_class . '"' : 'full-section'; ?>>
	<div class="heading">
		<h2>IPMI Controls</h2>
		<div class="actions">
			<?
				if($status == 1 || $status == 3) {
			?>
					<input type="button" class="ipmi_button lift_button" data-status="lift" value="Lift Null Route" />
			<?
				} else if($status == 2) {
			?>
					<input type="button" class="ipmi_button renew_button" data-status="renew" value="Renew Lift" />
					<input type="button" class="ipmi_button replace_button" data-status="replace" value="Replace Null Route" />
			<?
				} //end if
			?>
		</div>
		<div class="clear"></div>
	</div>

	<div class="clear"></div>
	<div>
		<strong><? echo $ipmi_message; ?></strong>
	</div>
	
	<form id="control-ipmi-form" action="<?php echo $control_device_url; ?>" method="POST">

		<input type="hidden" name="ipmi_action" />
		<input type="hidden" name="device_id" value="<?php echo $device_id; ?>" />
	</form>
</div>

<script type="text/javascript">
	$(document).ready(function() {
		var form = $('#control-ipmi-form'),
		button = $('.ipmi_button'),
		liftDialog = $('#lift_dialog'),
		replaceDialog = $('#replace_dialog'),
		renewDialog = $('#renew_dialog');

		liftDialog.dialog({
			autoOpen: false,
			width: 310,
			modal: true,
			resizable: false,
			buttons: {
				Confirm: function() {
					form.submit();
				},
				Cancel: function() {
					dialog.dialog('close');
				}
			}
		});

		replaceDialog.dialog({
			autoOpen: false,
			width: 310,
			modal: true,
			resizable: false,
			buttons: {
				Confirm: function() {
					form.submit();
				},
				Cancel: function() {
					dialog.dialog('close');
				}
			}
		});

		renewDialog.dialog({
			autoOpen: false,
			width: 310,
			modal: true,
			resizable: false,
			buttons: {
				Confirm: function() {
					form.submit();
				},
				Cancel: function() {
					dialog.dialog('close');
				}
			}
		});

		button.on('click',function(e) {
			var button = $(this);
			var status = button.data('status');
			form.find('input[name="ipmi_action"]').val(status);

			if(status == 'lift') {
				liftDialog.dialog('open');
			} else if(status == 'replace') {
				replaceDialog.dialog('open');
			} else if(status == 'renew') {
				renewDialog.dialog('open');
			}

			e.preventDefault();
			return false;
		});
	});
</script>

<div id="lift_dialog" title="Lift Null Route">
	<p>Are you sure you want to lift this null route?</p>
	<br>
	<p>It will be automatically replaced in 4 hours. The lift may be renewed for a new 4 hour period at any time from this page.</p>
</div>

<div id="replace_dialog" title="Relace Null Route">
	<p>Are you sure you want to replace this null route?</p>
	<br>
	<p>Note that it may take up to 2 minutes to show the change on this page.</p>
</div>

<div id="renew" title="Renew Null Route Lift">
	<p>Are you sure you want to renew this lift?</p>
	<br>
	<p>The null route will be automatically replaced 4 hours from now.</p>
</div>