<?php
	$control_device_url = ColoCrossing_Utilities::buildUrl($base_url, array(
		'controller' => 'devices',
		'action' => 'ipmi'
	));
?>

<div <?php echo isset($container_class) ? 'class="' . $container_class . '"' : 'full-section'; ?>>
	<div class="heading">
		<h2>IPMI Controls</h2>
		<div class="actions">
			<input type="button" class="control-ipmi-button button" data-status="lift" value="Lift Null Route" />
			<input type="button" class="control-ipmi-button button" data-status="renew" value="Renew Lift" />
			<input type="button" class="control-ipmi-button button" data-status="replace" value="Replace Null Route" />
		</div>
		<div class="clear"></div>
	</div>
	<form id="control-ipmi-form" action="<?php echo $control_device_url; ?>" method="POST">

		<input type="hidden" name="ipmi_action" />
		<input type="hidden" name="origin_device_id" value="<?php echo $device_id; ?>" />
	</form>
</div>

<script type="text/javascript">
	$(document).ready(function() {
		var form = $('#control-ipmi-form'),
		button = $('.control-ipmi-button'),
		dialog = $('#control-ipmi-dialog');

		dialog.dialog({
			autoOpen: false,
			width: 310,
			modal: true,
			resizable: false,
			buttons: {
				Confirm: function() {
					form.submit();
				},
				Cancel: function() {
					dialog.dialog('close');
				}
			}
		});

		button.on('click',function(e) {
			var button = $(this);

			form.find('input[name="ipmi_action"]').val(button.data('status'));
			dialog.dialog('open');

			e.preventDefault();
			return false;
		});
	});
</script>

<div id="control-ipmi-dialog" title="Control Power Ports">
	<p>Are you sure you want to <span class="action-description"></span>?</p>
</div>
