<?php
	$control_device_url = ColoCrossing_Utilities::buildUrl($base_url, array(
		'controller' => 'devices',
		'action' => 'update-power-ports'
	));
?>

<div class="<?php echo isset($container_class) ? $container_class : 'full-section'; ?>">
	<div class="heading">
		<h2>Power Ports</h2>
		<div class="actions">
			<input type="button" class="control-power-ports-button button" data-status="on" value="Turn On" />
			<input type="button" class="control-power-ports-button button" data-status="off" value="Turn Off" />
			<input type="button" class="control-power-ports-button button" data-status="restart" value="Restart" />
		</div>
		<div class="clear"></div>
	</div>
	<form id="control-power-ports-form" action="<?php echo $control_device_url; ?>" method="POST">
		<table class="datatable">
			<tr>
				<th style="width: 60px;">Control</th>
				<th>Device</th>
				<th>Port</th>
				<th>Status</th>
				<th>Comment</th>
			</tr>
		<?php
			$pdu_id = $pdu->getId();
			$pdu_ports = $pdu->getPorts();
			$pdu_devices = $pdu->getDevices(array('format' => 'map'));

			if(count($pdu_ports) == 0):
		?>
			<tr>
				<td colspan="5">No power ports configured.</td>
			</tr>
		<?php
			endif;

			foreach ($pdu_ports as $i => $port):
				$port_id = $port->getId();
				$port_status = $port->getStatus();
				$port_comment = $port->getComment();

				$control_status = $port->isControllable() ? '' : 'disabled';
				$control_name = 'power_distribution_units[' . $pdu_id . '][' . $port_id . ']';

				if($port->isAssignedToDevice()) {
					$device_id = $port->getDeviceId();
					$device = $pdu_devices[$device_id];

					if(isset($device)) {
						$device_url = ColoCrossing_Utilities::buildUrl($base_url, array(
							'controller' => 'devices',
							'action' => 'view',
							'id' => $device_id
						));

						$device_display = '<a href="' . $device_url . '">' . $device->getName() . '</a>';
					} else {
						$control_status = 'disabled';
						$device_id = 0;
						$device_display = 'Unknown';
					}
				} else {
					$control_status = 'disabled';
					$device_id = 0;
					$device_display = 'Unassigned';
				}
		?>
			<tr>
				<td>
					<label style="display: block;">
						<input type="checkbox" class="select-port-toggle" name="<?php echo $control_name; ?>"
							   value="<?php echo $device_id; ?>" <?php echo $control_status; ?>/>
					</label>
				</td>
				<td><?php echo $device_display; ?></td>
				<td><?php echo $port->getDescription(); ?></td>
				<td><?php echo isset($port_status) ? $port_status : 'Unknown'; ?></td>
				<td><?php echo isset($port_comment) ? $port_comment : ''; ?></td>
			</tr>
		<?php
			endforeach;
		?>
		</table>

		<input type="hidden" name="status" />
		<input type="hidden" name="comment" />
		<input type="hidden" name="origin_device_id" value="<?php echo $pdu_id; ?>" />
	</form>
</div>

<script type="text/javascript">
	$(document).ready(function() {
		var form = $('#control-power-ports-form'),
		table = form.find('table'),
		button = $('.control-power-ports-button'),
		dialog = $('#control-power-ports-dialog');

		dialog.dialog({
			autoOpen: false,
			width: 310,
			modal: true,
			resizable: false,
			buttons: {
				Confirm: function() {
					var comment = dialog.find('input[name="comment"]').val();

					form.find('input[name="comment"]').val(comment);
					form.submit();
				},
				Cancel: function() {
					dialog.dialog('close');
				}
			}
		});

		button.on('click',function(e) {
			var button = $(this),
			numSelected = table.find('.select-port-toggle:checked').length;

			if(numSelected > 0) {
				form.find('input[name="status"]').val(button.data('status'));
				dialog.find('.status-description').html(button.val().toLowerCase());
				dialog.dialog('open');
			} else {
				alert('Please select one or more power ports to ' + button.val().toLowerCase() + '.');
			}

			e.preventDefault();
			return false;
		});
	});
</script>

<style type="text/css">
	div.field-group { float: left; margin: 5px 0px; }
	div.field-group label { float: left; width: 120px; }
	div.field-group input { float: left; width: 150px; }
</style>

<div id="control-power-ports-dialog" title="Control Power Ports">
	<p>Are you sure you want to <span class="status-description"></span> these power ports?</p>
	<div class="field-group">
		<label>Comment:</label>
		<input type="text" name="comment" maxlength="20"/>
	</div>
</div>
