<div class="<?php echo isset($container_class) ? $container_class : 'full-section'; ?>">
	<h2>Subnets</h2>

	<table class="datatable">
		<tr>
			<th>IP Address</th>
			<th>SWIP</th>
		</tr>
	<?php
		if(count($subnets) == 0):
	?>
		<tr>
			<td colspan="2">No subnets found.</td>
		</tr>
	<?php
		endif;

		foreach ($subnets as $index => $subnet):
			$id = $subnet->getId();
			$url = ColoCrossing_Utilities::buildUrl($base_url, array(
				'controller' => 'subnets',
				'action' => 'view',
				'id' => $id
			));
	?>
		<tr>
			<td><a href="<?php echo $url; ?>"><?php echo $subnet->getCIDRIpAddress(); ?></a></td>
			<td><?php echo $subnet->isSwip() ? 'Yes' : 'No'; ?></td>
		</tr>
	<?php
		endforeach;
	?>
	</table>
</div>
