<?php
	$num_records = $this->devices->getTotalRecordCount();
	$num_pages = $this->devices->size();

	$columns = array(
		'name' => 'Name',
		'nickname' => 'Nickname',
		'type' => 'Type',
		'hostname' => 'Hostname',
		'subzone' => 'Zone',
		'rack' => 'Rack'
	);
	$sortable_columns = array('name', 'nickname', 'type', 'hostname');
?>

<form id="devices-table-form" method="get">
	<div>
		<h1 style="display: inline-block;">ColoCrossing Devices</h1>
		<div style="float: right;">
			<input type="text" name="query" value="<?php echo $this->filters['query']; ?>" />
			<input type="submit" value="Search" class="btn-small" />
		</div>
	</div>

<?php
	$this->renderFlashMessage();
?>

	<table width="100%" border="0" cellpadding="3" cellspacing="0">
		<tr>
			<td width="50%" align="left"><?php echo $num_records . ' Records Found, Page ' . $this->page . ' of ' . $num_pages ?></td>
			<td width="50%" align="right">
				<label>Jump to Page:</label>
				<select id='page-select'>
				<?php
					for ($page = 1; $page <= $num_pages; $page++) {
						echo '<option value="' . $page . '" ' . ($this->page == $page ? 'selected' : null) . '>' . $page . '</option>';
					}
				?>
				</select>
				<input type="submit" value="Go" class="btn-small">
			</td>
		</tr>
	</table>

	<div class="tablebg">
		<table class="datatable" width="100%" border="0" cellspacing="1" cellpadding="3" style="text-align: center;">
			<tr>
			<?php
				foreach ($columns as $id => $name) {
					if(in_array($id, $sortable_columns)) {
						$image = $this->sort == $id ? '<img src="images/' . $this->order . '.gif" class="absmiddle">' : '';
						echo '<th><a class="sort-column-button" href="#sort" data-sort="' . $id . '">' . $name . '</a> ' . $image . '</th>';
					} else {
						echo '<th>' . $name . '</th>';
					}
				}
			?>
			</tr>
		<?php
			if(count($this->devices->current()) == 0):
		?>
			<tr>
				<td colspan="6">No devices found.</td>
			</tr>
		<?php
			endif;

			foreach ($this->devices->current() as $index => $device):
				$type = $device->getType();
				$url = $this->base_url . '&controller=devices&action=view&id=' . $device->getId();

				if($type->isRacked()) {
					$rack_id = $device->getRackId();
					$rack_name = $device->getRackName();
					$rack_owner = $device->getRackOwner();

					if(isset($rack_id) && isset($rack_name) && isset($rack_owner)) {
						$rack_url = $this->base_url . '&controller=devices&action=view&id=' . $rack_id;
						$rack_name = '<a href="' . $rack_url . '">' . $rack_name . '</a>';
					}
				} else {
					$rack_name = 'Self';
				}
		?>
			<tr>
				<td><a href="<?php echo $url; ?>"><?php echo $device->getName(); ?></a></td>
				<td><?php echo $device->getNickname(); ?></td>
				<td><?php echo $type->getName(); ?></td>
				<td><?php echo $device->getHostname(); ?></td>
				<td><?php echo $device->getSubzone(); ?></td>
				<td><?php echo isset($rack_name) ? $rack_name : 'Unassigned'; ?></td>
			</tr>
		<?php
			endforeach;
		?>
		</table>
	</div>

	<p align="center">
	<?php
		if($this->page > 1) {
			echo '<a id="previous-page-button" href="#previous-page">&laquo; Previous Page</a>';
		} else {
			echo '<span id="previous-page-button">&laquo; Previous Page</span>';
		}

		echo '&nbsp;';

		if($this->page < $num_pages) {
			echo '<a id="next-page-button" href="#next-page">Next Page &raquo;</a>';
		} else {
			echo '<span id="next-page-button">Next Page &raquo;</span>';
		}
	?>
	</p>

	<input type="hidden" name="module" value="colocrossing" />
	<input type="hidden" name="controller" value="devices" />
	<input type="hidden" name="action" value="index" />
	<input type="hidden" name="sort" value="<?php echo $this->sort; ?>" />
	<input type="hidden" name="order" value="<?php echo $this->order; ?>" />
	<input type="hidden" name="page" value="<?php echo $this->page; ?>" />
</form>

<script type="text/javascript">

	$(document).ready(function() {

		$('#contentarea, #content').find('h1').first().remove();

		var currentPage = parseInt('<?php echo $this->page; ?>'),
		form = $('#devices-table-form'),
		sortInput = form.find('input[name="sort"]'),
		orderInput = form.find('input[name="order"]'),
		pageInput = form.find('input[name="page"]');

		form.find('a.sort-column-button').on('click', function(e) {
			var button = $(this);

			if(button.data('sort') == sortInput.val()) {
				orderInput.val(orderInput.val() == 'asc' ? 'desc' : 'asc');
			} else {
				sortInput.val(button.data('sort'));
				orderInput.val('asc');
			}

			form.submit();

			e.preventDefault();
			return false;
		});

		form.find('a#previous-page-button').on('click', function(e) {
			pageInput.val(currentPage - 1);
			form.submit();

			e.preventDefault();
			return false;
		});

		form.find('a#next-page-button').on('click', function(e) {
			pageInput.val(currentPage + 1);
			form.submit();

			e.preventDefault();
			return false;
		});

		form.find('select#page-select').on('change', function() {
			pageInput.val($(this).val());
			form.submit();

			e.preventDefault();
			return false;
		});

	});

</script>

<style type="text/css">
	div#contentarea h1 { margin-bottom: 10px; }
</style>