<?php
	$columns = array(
		'name' => 'Name',
		'nickname' => 'Nickname',
		'type' => 'Type',
		'hostname' => 'Hostname',
		'subzone' => 'Zone',
		'rack' => 'Rack',
		'due_date' => 'Due Date',
		'status' => 'Status',
		'assignment' => 'Assignment'
	);
	$sortable_columns = array('name', 'nickname', 'type', 'hostname', 'subzone');
?>

<form id="devices-table-form" method="get">
	<div class="heading">
		<h2>Affected Devices</h2>
	</div>

	<table width="100%" border="0" cellpadding="3" cellspacing="0">
		<tr>
			<td width="50%" align="left"><?php echo $this->num_records . ' Records Found, Page ' . $this->page_number . ' of ' . $this->num_pages ?></td>
			<td width="50%" align="right">
				<label>Show</label>
				<select id='page-size-select' name="page_size">
					<option <?php echo $this->page_size == 5 ? 'selected' : null; ?>>5</option>
					<option <?php echo $this->page_size == 50 ? 'selected' : null; ?>>50</option>
					<option <?php echo $this->page_size == 100 ? 'selected' : null; ?>>100</option>
					<option <?php echo $this->page_size == 250 ? 'selected' : null; ?>>250</option>
					<option <?php echo $this->page_size == 500 ? 'selected' : null; ?>>500</option>
				</select>
				<label>devices</label>
			</td>
		</tr>
	</table>

	<div class="tablebg">
		<table class="datatable" width="100%" border="0" cellspacing="1" cellpadding="3" style="text-align: center;">
			<tr>
			<?php
				foreach ($columns as $id => $name) {
					if(in_array($id, $sortable_columns)) {
						$image = $this->sort == $id ? '<img src="images/' . $this->order . '.gif" class="absmiddle">' : '';
						echo '<th><a class="sort-column-button" href="#sort" data-sort="' . $id . '">' . $name . '</a> ' . $image . '</th>';
					} else {
						echo '<th>' . $name . '</th>';
					}
				}
			?>
			</tr>
		<?php
			if(count($devices) == 0):
		?>
			<tr>
				<td colspan="7">No devices found.</td>
			</tr>
		<?php
			endif;

			foreach ($devices as $index => $device):
				$device_id = $device->getId();
				$device_url = ColoCrossing_Utilities::buildUrl($base_url, array(
					'controller' => 'devices',
					'action' => 'view',
					'id' => $device_id
				));
				$device_type = $device->getType();
				$device_assignment = 'Unassigned';

				$service = isset($services[$device_id]) ? $services[$device_id] : null;

				$service_due_date = 'N/A';
				$service_status = 'N/A';

				$client = isset($service) ? $service->getClient(): null;

				if(isset($service) && isset($client)) {
					$client_service_url = ColoCrossing_Utilities::buildUrl('clientsservices.php', array(
						'id' => $service->getId(),
						'userid' => $client->getId()
					));

					$service_due_date = $service->getFormattedDueDate();
					$service_status = $service->getStatus();

					$device_assignment = '<a href="' . $client_service_url . '">' . $client->getFullName() . '</a>';
				}

				if($device_type->isRacked()) {
					$rack_id = $device->getRackId();
					$rack_name = $device->getRackName();
					$rack_owner = $device->getRackOwner();

					if(isset($rack_id) && isset($rack_name) && isset($rack_owner)) {
						$rack_url = ColoCrossing_Utilities::buildUrl($base_url, array(
							'controller' => 'devices',
							'action' => 'view',
							'id' => $rack_id
						));
						$rack_name = '<a href="' . $rack_url . '">' . $rack_name . '</a>';
					}
				} else {
					$rack_name = 'Self';
				}
		?>
			<tr>
				<td><a href="<?php echo $device_url; ?>"><?php echo $device->getName(); ?></a></td>
				<td><?php echo $device->getNickname(); ?></td>
				<td><?php echo $device_type->getName(); ?></td>
				<td><?php echo $device->getHostname(); ?></td>
				<td><?php echo $device->getSubzone(); ?></td>
				<td><?php echo isset($rack_name) ? $rack_name : 'Unassigned'; ?></td>
				<td><?php echo $service_due_date ?></td>
				<td><?php echo $service_status ?></td>
				<td><?php echo $device_assignment; ?></td>
			</tr>
		<?php
			endforeach;
		?>
		</table>
	</div>

	<p align="center">
	<?php
		if($this->page_number > 1) {
			echo '<a id="previous-page-button" href="#previous-page">&laquo; Previous Page</a>';
		} else {
			echo '<span id="previous-page-button">&laquo; Previous Page</span>';
		}

		echo '&nbsp;';

		if($this->page_number < $this->num_pages) {
			echo '<a id="next-page-button" href="#next-page">Next Page &raquo;</a>';
		} else {
			echo '<span id="next-page-button">Next Page &raquo;</span>';
		}
	?>
	</p>

	<input type="hidden" name="module" value="colocrossing" />
	<input type="hidden" name="controller" value="announcements" />
	<input type="hidden" name="action" value="view" />
	<input type="hidden" name="id" value="<?php echo $announcement->getId(); ?>" />
	<input type="hidden" name="sort" value="<?php echo $this->sort; ?>" />
	<input type="hidden" name="order" value="<?php echo $this->order; ?>" />
	<input type="hidden" name="page_number" value="<?php echo $this->page_number; ?>" />
</form>

<script type="text/javascript">

	$(document).ready(function() {
		var currentPage = parseInt('<?php echo $this->page_number; ?>'),
		form = $('#devices-table-form'),
		sortInput = form.find('input[name="sort"]'),
		orderInput = form.find('input[name="order"]'),
		pageNumberInput = form.find('input[name="page_number"]'),
		pageSizeInput = form.find('select[name="page_size"]');

		pageSizeInput.on('change', function(e) {
			pageNumberInput.val(1);
			form.submit();

			e.preventDefault();
			return false;
		});

		form.find('a.sort-column-button').on('click', function(e) {
			var button = $(this);

			if(button.data('sort') == sortInput.val()) {
				orderInput.val(orderInput.val() == 'asc' ? 'desc' : 'asc');
			} else {
				sortInput.val(button.data('sort'));
				orderInput.val('asc');
			}

			form.submit();

			e.preventDefault();
			return false;
		});

		form.find('a#previous-page-button').on('click', function(e) {
			pageNumberInput.val(currentPage - 1);
			form.submit();

			e.preventDefault();
			return false;
		});

		form.find('a#next-page-button').on('click', function(e) {
			pageNumberInput.val(currentPage + 1);
			form.submit();

			e.preventDefault();
			return false;
		});

	});

</script>
