<?php
  $columns = array(
    'subject' => 'Subject',
    'type' => 'Type',
    'severity' => 'Severity',
    'start_at' => 'Start At',
    'end_at' => 'End At',
    'created_at' => 'Created At'
  );
  $sortable_columns = array('type', 'severity', 'subject', 'start_at', 'end_at', 'created_at');
?>

<form id="announcements-table-form" method="get">
  <div style="float: right;">
    <input type="text" name="query" value="<?php echo $this->filters['query']; ?>" />
    <input type="submit" value="Search" class="btn-small" />
  </div>
  <h1>ColoCrossing Announcements</h1>

<?php
  $this->renderFlashMessage();
?>

  <table width="100%" border="0" cellpadding="3" cellspacing="0">
    <tr>
      <td width="50%" align="left"><?php echo $this->num_records . ' Records Found, Page ' . $this->page . ' of ' . $this->num_pages ?></td>
      <td width="50%" align="right">
        <label>Jump to Page:</label>
        <select id='page-select'>
        <?php
          for ($page = 1; $page <= $this->num_pages; $page++) {
            echo '<option value="' . $page . '" ' . ($this->page == $page ? 'selected' : null) . '>' . $page . '</option>';
          }
        ?>
        </select>
        <input type="submit" value="Go" class="btn-small">
      </td>
    </tr>
  </table>

  <div class="tablebg">
    <table class="datatable" width="100%" border="0" cellspacing="1" cellpadding="3" style="text-align: center;">
      <tr>
      <?php
        foreach ($columns as $id => $name) {
          if(in_array($id, $sortable_columns)) {
            $image = $this->sort == $id ? '<img src="images/' . $this->order . '.gif" class="absmiddle">' : '';
            echo '<th><a class="sort-column-button" href="#sort" data-sort="' . $id . '">' . $name . '</a> ' . $image . '</th>';
          } else {
            echo '<th>' . $name . '</th>';
          }
        }
      ?>
      </tr>
    <?php
      if(count($this->announcements) == 0):
    ?>
      <tr>
        <td colspan="6">No announcements found.</td>
      </tr>
    <?php
      endif;

      foreach ($this->announcements as $index => $announcement):
        $id = $announcement->getId();
        $url = ColoCrossing_Utilities::buildUrl($this->base_url, array(
          'controller' => 'announcements',
          'action' => 'view',
          'id' => $id
        ));
        $type = $announcement->getType();
        $severity = $announcement->getSeverity();

        $start_at = $announcement->getStartDate();
        $end_at = $announcement->getEndDate();
        $created_at = $announcement->getCreateDate();
    ?>
      <tr>
        <td><a href="<?php echo $url; ?>"><?php echo $announcement->getSubject(); ?></a></td>
        <td><?php echo $type->getName(); ?></td>
        <td><?php echo $severity->getName(); ?></td>
        <td><?php echo empty($start_at) ? 'N/A' : date('m/d/Y h:i a', $start_at); ?></td>
        <td><?php echo empty($end_at) ? 'N/A' : date('m/d/Y h:i a', $end_at); ?></td>
        <td><?php echo empty($created_at) ? 'N/A' : date('m/d/Y', $created_at); ?></td>
      </tr>
    <?php
      endforeach;
    ?>
    </table>
  </div>

  <p align="center">
  <?php
    if($this->page > 1) {
      echo '<a id="previous-page-button" href="#previous-page">&laquo; Previous Page</a>';
    } else {
      echo '<span id="previous-page-button">&laquo; Previous Page</span>';
    }

    echo '&nbsp;';

    if($this->page < $this->num_pages) {
      echo '<a id="next-page-button" href="#next-page">Next Page &raquo;</a>';
    } else {
      echo '<span id="next-page-button">Next Page &raquo;</span>';
    }
  ?>
  </p>

  <input type="hidden" name="module" value="colocrossing" />
  <input type="hidden" name="controller" value="announcements" />
  <input type="hidden" name="action" value="index" />
  <input type="hidden" name="sort" value="<?php echo $this->sort; ?>" />
  <input type="hidden" name="order" value="<?php echo $this->order; ?>" />
  <input type="hidden" name="page" value="<?php echo $this->page; ?>" />
</form>

<script type="text/javascript">

  $(document).ready(function() {

    $('#contentarea, #content').find('h1').first().remove();

    var currentPage = parseInt('<?php echo $this->page; ?>'),
    form = $('#announcements-table-form'),
    sortInput = form.find('input[name="sort"]'),
    orderInput = form.find('input[name="order"]'),
    pageInput = form.find('input[name="page"]');

    form.find('a.sort-column-button').on('click', function(e) {
      var button = $(this);

      if(button.data('sort') == sortInput.val()) {
        orderInput.val(orderInput.val() == 'asc' ? 'desc' : 'asc');
      } else {
        sortInput.val(button.data('sort'));
        orderInput.val('asc');
      }

      form.submit();

      e.preventDefault();
      return false;
    });

    form.find('a#previous-page-button').on('click', function(e) {
      pageInput.val(currentPage - 1);
      form.submit();

      e.preventDefault();
      return false;
    });

    form.find('a#next-page-button').on('click', function(e) {
      pageInput.val(currentPage + 1);
      form.submit();

      e.preventDefault();
      return false;
    });

    form.find('select#page-select').on('change', function() {
      pageInput.val($(this).val());
      form.submit();

      e.preventDefault();
      return false;
    });

  });

</script>

<style type="text/css">
  div#contentarea h1 { margin-bottom: 10px; }
</style>
