<div style="margin: 0 10px;">
	<?php
		$this->renderFlashMessage();
	?>

	<table class="form" width="100%" border="0" cellspacing="2" cellpadding="3">
		<tr>
			<td width="15%" class="fieldlabel">Name</td>
			<td width="35%" class="fieldarea"><?php echo $this->device->getName(); ?></td>
			<td width="15%" class="fieldlabel">Zone</td>
			<td width="35%" class="fieldarea"><?php echo $this->device->getSubzone(); ?></td>
		</tr>
		<tr>
			<td width="15%" class="fieldlabel">Type</td>
			<td width="35%" class="fieldarea"><?php echo $this->type->getName(); ?></td>
		</tr>
	</table>

<?php
	$this->renderTemplate('/sales-devices/_assets.phtml', array(
		'assets' => $this->assets
	));
?>

	<div class="clear"></div>
</div>

<script type="text/javascript">
	$(document).ready(function() {
		$('#contentarea, #content').find('h1').html('ColoCrossing Device - <?php echo $this->device->getName(); ?>');
	});
</script>

<style type="text/css">
	div#contentarea h2 { margin-bottom: 10px; }

	div.heading { margin-bottom: 0px; margin-top: 5px; padding: 5px 0px; }
	div.heading h2 { float: left; margin-top: 5px; margin-bottom: 5px !important; }

	table.datatable { width: 100%; text-align: center; }
</style>
