<div class="page-header">
    <div class="styled_title"><h1>An Error Has Occurred!</h1></div>
</div>

<?php
	$this->renderFlashMessage();

	if(empty($this->message)) {
		$this->message = 'An error occured while trying to load this page. Please try again later.';
	}

	echo '<p>' . $this->message . '</p>';
?>

<style type="text/css">
    .header-lined { display: none; }
    .page-header { margin-top: 0px; }
</style>
